### ISSUE TITLE
Expanding the left bar (GQL editor) affects the right pane

### ISSUE THREAD

**Issue by tvvignesh** [graphql-editor/graphql-editor#118]
When the left pane (where we type in the GraphQL query) is expanded/resized - it affects the click event on the right side (screenshot below). You will notice that the element hover event/click event gets triggered when I have not moved the mouse over the element (this is because I had resized the left pane)

![Screenshot from 2019-08-04 16-26-28](https://user-images.githubusercontent.com/1165845/62422729-adfef500-b6d4-11e9-970c-52bb328fb442.png)

**Comment by aexol** [comment]
@hzub - can you check it this/next week?
