### ISSUE TITLE
how to update schema

### ISSUE THREAD

**Issue by nileio** [graphql-editor/graphql-editor#120]
hi guys,
I am struggling with a basic thing .. i am getting the schema from a remote api and use the following code in my component
```
  componentDidMount() {
    this.getSchema();
  }
  async getSchema() {
     // await get my schema from remote url
      this.setState({
        schema: schema
      });
    }
  }
  render() {
    return (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "grid",
          gridTemplateColumns: this.state.editorVisible ? `auto 1fr` : "1fr",
          gridTemplateRows: "1fr"
        }}
      >
        <Editor editorVisible={this.state.editorVisible} schema={this.state.schema} />
      </div>
    );
  }
```
I verified that my schema is valid and returns correctly from the remote API .. and I tried multiple ways but the component does not update with the new schema. what am i doing wrong ? how can I dynamically update the schema please ?

thank you!!

**Comment by nileio** [comment]
for anyone facing similar issue .. I think the Editor component has a bug and does not render updated schema though the schema is parsed correctly. I tried all sort of things.

The workaround/solution for me was to conditionally render the component from a parent component. once the component is rendered it cannot (with my tests and limited knowledge of this) be updated with a new schema. the component need to be remounted.. please comment and correct me if i am wrong.. cheers

**Comment by aexol** [comment]
@nileio I've already responded on slack how to do it. Just check slack before writing that it doesnt work
