### ISSUE TITLE
Ability to work with type based graph only

### ISSUE THREAD

**Issue by wtrocki** [graphql-editor/graphql-editor#123]
GraphQL-Editor seems to be nice tool, but is not that useful for production use cases where large schema prevents from getting the overview.

Having filtering capability with possible options like:

- Show types only
- Show operations

will be really useful to get it for more production use cases.

**Comment by aexol** [comment]
Great idea we will do that! @wtrocki

**Comment by aexol** [comment]
btw you have Ctrl+F in latest release so you can search graph this way

**Comment by wtrocki** [comment]
@aexol Great. This feature is so useful that we might close this issue. However making this more prominent in UX will be cool.  Graphiql has shortcuts button that shows all the shortcuts.
