### ISSUE TITLE
[Pricing] Provide a free plan for public OSS teams

### ISSUE THREAD

**Issue by talentlessguy** [graphql-editor/graphql-editor#127]
# Problem

This may be subjective, but still. Regularly, development services are free for public usage and paid for private. GraphQL editor will be paid even if you use it in a public team.

I don't think it is fair to make such option paid because a team doesn't use private projects.

# Solution

It would be nice if GraphQL editor provided **a free OSS plan for public-only teams with up to 3 editors**. Similar to **Team Plan** but with less options because it is free. The only option we need currently is allowing 3 editors to work on the same project.

If this issue will be closed and there still won't be an option to provide a free team project, we sadly have to move to some other similar tools.

# Additional context

Our board is [here](https://app.graphqleditor.com/komfy/komfy-api) to ensure it is public
Our project is [here](https://github.com/komfy) to ensure we are OSS

**Comment by aexol** [comment]
We will provide a discount for OSS teams and Educational institutions in the future. We just need to check how to do it and ask our advisors. Contact me by intercom or email, please.

**Comment by talentlessguy** [comment]
@aexol thanks for responding to an issue!

In my opinion, OSS teams should be free and have a very limited functionality, for example creating only one namespace, 2 boards maximum and up to 3 team members so this plan won't abuse anything.

"Students" plan sounds cool.

Our team **really** likes GraphQL editor and has been using it since starting working on API so we look forward for such plan to be present.

I'll copy paste this text to email :)

**Comment by aexol** [comment]
@talentlessguy Good things are coming - I think we will have an Open Source plan for public projects and storage. But we cannot provide collaboration for free right now. If you have more suggestions, this is a good moment for them :)

**Comment by talentlessguy** [comment]
@aexol 

## In the future

my suggestion is still adding collaboration for OSS teams but with 3 members max and other limits like no any private boards so it will be fair

## Now

Allow creating one namespace for a free account maybe?

because currently I can't even create a new project

![image](https://user-images.githubusercontent.com/35937217/69542333-4a0e7e00-0f9c-11ea-9363-f0de56de2e38.png)

![image](https://user-images.githubusercontent.com/35937217/69542352-5397e600-0f9c-11ea-9294-69e16cb9e045.png)

**Comment by aexol** [comment]
Thanks for the fast response. I will notify you here when we roll out 1 free namespace with 2 public projects. Have a nice day!

**Comment by aexol** [comment]
@talentlessguy 
https://nightly.graphqleditor.com/ - Here is the new version we are about to ship to production tomorrow. Can you check it out today or tomorrow morning?

**Comment by talentlessguy** [comment]
> @talentlessguy
> https://nightly.graphqleditor.com/ - Here is the new version we are about to ship to production tomorrow. Can you check it out today or tomorrow morning?

looks dope! 

The only problem is that I can't use namespaces I created before... at least they aren't listed anywhere (namespace is called `komfy`, I recently deleted one of its boards)

**Comment by aexol** [comment]
Closing as of latest release covering mock backend in free plan
