### ISSUE TITLE
Types implementing interfaces should have fields of interface

### ISSUE THREAD

**Issue by eljenso** [graphql-editor/graphql-editor#17]
Have the following graph:
![selection_186](https://user-images.githubusercontent.com/2805194/46090230-8dab0380-c1b0-11e8-8131-ef6c2a2dd7b8.png)
Which generates the following schema:
```
interface IElement{
	name: String!,
	id: ID!
}
type thing implements IElement{
	enabled: Boolean
}
```

But the way interfaces in GraphQL work is that fields of the interface should also be present in the implementation (https://graphql.org/learn/schema/#interfaces).
Hence, I think the schema should look something like this:
```
interface IElement{
	name: String!,
	id: ID!
}
type thing implements IElement{
	name: String!,
	id: ID!,
	enabled: Boolean
}
```

**Comment by aexol** [comment]
Consider it done! I will commit changes in few hours with correct interfaces. Thank you!
