### ISSUE TITLE
AWS Amplify Support

### ISSUE THREAD

**Issue by czaku** [graphql-editor/graphql-editor#179]
Hi,

Is the support for AWS Amplify - AppSync GraphQL schema something on the roadmap?

At the moment pasting my schema it doesn't want to compile due to certain types specific to AWS

**Comment by aexol** [comment]
AWS Amplify is not compliant with GraphQL Spec :D . If you use GraphQL Editor online version you can add a library with Amplify definitions :

https://app.graphqleditor.com/explore-projects/aws-amplify
