### ISSUE TITLE
Defect: Unable to consistently show the node pop up menu

### ISSUE THREAD

**Issue by bigman73** [graphql-editor/graphql-editor#211]
I'm trying to create fields on a type, visually.
It is very hard to activate the node pop up menu when left clicking on the left triangle area on the node using the visual editor. 
Only once in a few dozens of times does the menu pops up.
In the rest of the times there is a rectangle showing underneath the node.
This is reproducible with Chrome and Firefox.

Right clicking the node shows a pop up menu, but it is another pop up menu that doesn't allow creation of fields.

See in screenshot, a white rectangle show under the node, but no pop up. The cursor is hidden but it on the little triangle on the Person node, with the light grey background:
![image](https://user-images.githubusercontent.com/5384551/92770054-90846c00-f367-11ea-866d-36da464b4486.png)

The expected behavior:
![image](https://user-images.githubusercontent.com/5384551/92779639-3dfb7d80-f370-11ea-93ef-0ccbe459da32.png)

**Comment by aexol** [comment]
Check the branch `jsx`. We are doing completly new editor ;)

**Comment by bigman73** [comment]
Thanks for pointing out the jsx branch.
I just played with it and it works but I don't understand why the original 'UML class diagram style' diagram was abandoned. Both views have place. The new diagram/view organizes things better but is not useful for immediate big picture exploration of the whole schema.

**Comment by aexol** [comment]
Thanks big man!  I worked with medium and big-sized schemas that are unreadable using the graph. I will try hard to implement relations on the new branch. I want to add an expand-all option and draw relations somehow inside the new view and using renderer(jsx react) which is maintainable. If you have any ideas right now I am open to it.

**Comment by aexol** [comment]
@bigman73 
any suggestions?

**Comment by bigman73** [comment]
I simply suggest two views: (follows the MVC pattern with one model for both):
1. Organizer view - the new view you implemented. Easy to find things, well organized
2. Entity diagram view - the old view but enhanced for easy navigation of large diagrams. Provides a holistic view of the data model which is very common with ERD and UML Class Diagrams.

Another improvement to 2 would be keeping subset/slice. Maybe out of 100 entities (types, etc.) I only want to have 5 types and call that view 'People types'. The definition of those views and other preferences could be kept in a separate file or as comments within the GraphQL file.

**Comment by aexol** [comment]
@bigman73 Closing this issue. I've added the old graph in readonly mode with enhanced visuals in new version of editor.

**Comment by aexol** [comment]
Thanks for your suggestions of course!
