### ISSUE TITLE
Error: type  { onSchemaChange : (props : SetStateAction<PassedSchema>)  => void ; schema  : PassesSchema ;}' is not assignable to type 'IntrinsicAttributes & EditorProps'. when I have tried to install the software locally on the PC 

### ISSUE THREAD

**Issue by bommojuvishu** [graphql-editor/graphql-editor#273]
I have setup the react project manually with webpack and typescript  . I have installed all the dependencies that document mentioned
npm i react react-dom monaco-editor
npm i -D monaco-editor-webpack-plugin worker-loader css-loader file-loader
npm i graphql-editor

`import React, { useState } from 'react';
import { render } from 'react-dom';
import { GraphQLEditor,PassedSchema } from 'graphql-editor';

const schemas = {
  pizza:`
type Query{
	pizzas: [Pizza!]
}
`,
pizzaLibrary:`
type Pizza{
  name:String;
}
`
}

export const App = () => {
  const [mySchema, setMySchema] = useState<PassedSchema>({
    code: schemas.pizza,
    libraries: schemas.pizzaLibrary,
  });
  return (
    <div
      style={{
        flex: 1,
        width: '100%',
        height: '100%',
        alignSelf: 'stretch',
        display: 'flex',
        position: 'relative',
      }}
    >
      <GraphQLEditor
        onSchemaChange={(props) => {
          setMySchema(props);
        }}
        schema={mySchema}
      />
    </div>
  );
};

render(<App />, document.getElementById('root'));
`

I am getting the following error :
**type  { onSchemaChange : (props : SetStateAction<PassedSchhema>)  => void ; schema  : PassesSchema ;}' is not assignable to type 'IntrinsicAttributes & EditorProps'. 
Property  'onSchemaChange ' does not exist on type ' IntrinsicAttributes & EditorProps'.** 

Please let me know if I am missing any steps  , or is there any issue

**Comment by kjuro** [comment]
I had the same error. I changed tag to:
```
<GraphQLEditor 
  schema={mySchema} 
  setSchema={function (props: PassedSchema, isInvalid?: boolean | undefined): void {
      setMySchema(props); 
   } }      
 />
```
This works but I have problem that editor is not visible.
