### ISSUE TITLE
Monaco Code Editor is not getting dynamically resized on self host graphql editor

### ISSUE THREAD

**Issue by arjunballa** [graphql-editor/graphql-editor#282]
Monaco editor is not getting resized based on the loaded schema. see height is 5px in screenshot attached.

You can reproduce using https://github.com/arjunballa/graphql-editor-create-react-app-example/

![image](https://user-images.githubusercontent.com/613351/131881155-817b75f3-fc54-4f7f-a33b-a295665d31ab.png)

**Comment by kjuro** [comment]
I have the same problem. Did someone find some solution for it?

**Comment by kjuro** [comment]
I fond solution. I added CSS styles:

```
html, body, #root {
  height: 100%;
  width: 100%;
}
```

Editor is shown now.

**Comment by nandeeshshankar** [comment]
@arjunballa  I ran the code in my local from the git link provided. It is up and running. I see some options are missing when it is compared with online editor link (https://graphqleditor.com/).

1. on the left pane, I am not able to edit the code.
2. I don't see any option to import from file or export.

Team, Any inputs here?
