### ISSUE TITLE
GraphQL Editor alternatives

### ISSUE THREAD

**Issue by ilyagru** [graphql-editor/graphql-editor#341]
Hello!

I'm doing some reserarch and trying to find similar tools to compare them. Could you please let me know if there any? 

Looking for something for GraphQL collaboration for both sides - Frontend and Backend developers - a collaborative platform/tool for GraphQL API design. Something that will simultaneously let Frontend developers write requirements (e.g. what data or query they need for UI) and Backend developers see and implement them. Basically for eliminating manual work and going back and forth, for the bigger picture of the schema too because these tools usually should render the schema as a graph/diagram to see available data and relationship.

graphqleditor.com is the most suitable one so far.

Thanks!

**Comment by aexol** [comment]
Have you found anything?

**Comment by ilyagru** [comment]
> Have you found anything?

Not really. :(

These tools, however, could somewhat complement but for GraphQL collaboration, it seems there are no such tools...

Platforms

- https://www.apollographql.com/platform (Studio)
- https://tyk.io/

Integration

- https://wundergraph.com/
- https://www.onegraph.com/

Graphs (but can be any suitable library for graphs)

- https://github.com/APIs-guru/graphql-voyager
- https://github.com/Novvum/graphql-birdseye
- https://github.com/yamafaktory/craftql

Debugging, testing and API client

- https://insomnia.rest/
- https://www.postman.com/
- https://altair.sirmuel.design/
- https://firecamp.io/
