### ISSUE TITLE
Optimize performance of Editor

### ISSUE THREAD

**Issue by aexol** [graphql-editor/graphql-editor#403]

**Comment by aexol** [comment]
Performance issues are only in:
- monaco editor
- relation view

**Comment by aexol** [comment]
- graphsource view

**Comment by cancan101** [comment]
I am curious how `graphsource` is being used by this package. I see it listed as a dependency in `package.json` but don't see it being used in the code itself: https://github.com/graphql-editor/graphql-editor/search?q=graphsource&type=code
