### ISSUE TITLE
Toogle Code Not Showing Schema

### ISSUE THREAD

**Issue by hugoupsam** [graphql-editor/graphql-editor#462]
The Toogle Code Clid & Unclick that no shows the schema code.

See the issue in the image uploaded.

Thanks in advance!!!!

<img width="717" alt="tooglecodeerror" src="https://user-images.githubusercontent.com/22373934/190444320-b1930791-e74f-466e-9c99-7cd002c6b01b.PNG">

**Comment by KenEucker** [comment]
I am also experiencing this issue and it is a bit of a blocker.

**Comment by KenEucker** [comment]
I was able to find a solution by searching this project's forks and finding an example that didn't have this issue. It was solved by adding this css:

```css
  html, body, #root {
    height: 100%;
    width: 100%;
  }
```

YMMV.
