### ISSUE TITLE
Not able to integrate GraphQL visual editor with reactjs

### ISSUE THREAD

**Issue by nandeeshshankar** [graphql-editor/graphql-editor#519]
Team,

   I installed the graphql dependency using the npm command and it got installed into my project. post that, I added the code which is available under GraphQL SDL Editor section but landed in below issue. please assist further.

Uncaught TypeError: ((react__WEBPACK_IMPORTED_MODULE_0__.useState < graphql_editor__WEBPACK_IMPORTED_MODULE_1__.PassedSchema) > (intermediate value)) is not iterable
    App App.js:20
    React 11
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24

**Comment by aexol** [comment]
Not a rich feedback here. Have you installed peer deps plugins?

**Comment by nandeeshshankar** [comment]
@aexol  I went through the document in the gut link and installed all the peer plugins correctly. It is up and running now but I have couple of things here. It would be great, if you can help me with the same.

1. On the left pane, I am unable to edit/modify the code.
2. I don't see any option to import from file or export. like how we have in online editor.
3. Relationship in tabular form in not getting displayed correctly. I am able to see the visual but no relationship is display among them.

**Comment by nandeeshshankar** [comment]
@aexol Can I get some updates please?
