### ISSUE TITLE
can we relate type field to some other fields in faker?

### ISSUE THREAD

**Issue by robmatyszewski** [graphql-editor/graphql-editor#72]

**Comment by aexol** [comment]
This one is complicated we should put it on Q3 roadmap

**Comment by robmatyszewski** [comment]
Cool, i said the same to the user.

**Comment by aexol** [comment]
Solution  is to take from :
```graphql
type Cat{
  image:String!
}
```
image will generate random image so we should consider generating from `Cat.image` instead of `image`
