### ISSUE TITLE
How to increase support for the prisma graphql syntax

### ISSUE THREAD

**Issue by limengsong** [graphql-editor/graphql-editor#97]
hi~
Now using the standard syntax of graphql, it can be visualized normally.
I hope to extend support for prisma graphql. This contains some instructions and types like:
```
type User implements Base {
  "用户ID"
  id: ID! @unique
  "用户名称，用户登录字段"
  name: String! @unique
  "用户邮箱，密码找回用"
  email: String! @unique @constraint(format: "email")
  "password"
  password: String! @clear(role:ADMIN)
  "用户角色组"
  role: Role! @default(value:USER)
  "用户组"
  group:UserGroup
  "RFID 可以为空不能重复"
  RFID:String @unique
  "用户对应人员"
  person:Person! @relation(name: "UserByPerson")
  "其他描述信息"
  description: String
  "用户状态"
  status:UserStatus! @default(value:ACTIVITY)
  "创建时间"
  createdAt: DateTime!
  "更新时间"
  updatedAt: DateTime!
}


```
thank you！

**Comment by aexol** [comment]
Hi,
You can use your Prisma syntax. Just define their directives inside your project.
https://graphql.github.io/graphql-spec/draft/#DirectiveDefinition

**Comment by aexol** [comment]
@limengsong

**Comment by limengsong** [comment]
@aexol 
In this graphql-editor project, where do you want to expand, please help me with a simple demonstration, thank you！

**Comment by aexol** [comment]
Find the prisma directives and paste them to your project
